#cloud-config
autoinstall:
  version: 1

# Update/upgrade the system first
package_update: true
package_upgrade: true

# Create the Nouveau blacklist (critical before driver install)
write_files:
  - path: /etc/modprobe.d/blacklist-nouveau.conf
    content: |
      blacklist nouveau
      blacklist lbm-nouveau
      options nouveau modeset=0
      alias nouveau off
      alias lbm-nouveau off
    permissions: '0644'

runcmd:
  - update-initramfs -u
  - add-apt-repository ppa:graphics-drivers/ppa -y
  - apt update -y
  - apt install -y nvidia-driver-595-server-open nvtop

power_state:
  mode: reboot
  message: "Rebooting to load NVIDIA drivers"
  timeout: 1
